# Generated by Django 5.1 on 2025-02-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
